title: Lending Club Case Study
description: |
    A case study by Srikanth Chakravarthy
    <br><br>
    <a href="https://www.linkedin.com/in/scorsagg/" style="color:white">LinkedIn</a>
theme: jekyll-theme-cayman
